/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package princetonPlainsboro;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.Reader;
import static java.lang.System.in;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Lydia
 */
public class InterfaceMedecin extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceMedecin
     */
    public InterfaceMedecin() {
        initComponents();
        initjList1();
        initJTextArea();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        jLabel9 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultation des patients");
        setBackground(new java.awt.Color(0, 204, 51));
        setMinimumSize(new java.awt.Dimension(750, 400));

        jSplitPane1.setBackground(new java.awt.Color(204, 255, 204));
        jSplitPane1.setDividerLocation(200);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 154));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(204, 255, 204));

        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel4.setLayout(new java.awt.GridLayout(3, 0));

        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Liste des patients");
        jPanel12.add(jLabel1, java.awt.BorderLayout.CENTER);

        jButton7.setText("Sans tri");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton7, java.awt.BorderLayout.LINE_END);

        jPanel4.add(jPanel12);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Saisir le médecin traitant pour faire le tri");
        jPanel11.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel11);

        jPanel13.setLayout(new java.awt.BorderLayout());

        jTextField1.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField1.setPreferredSize(new java.awt.Dimension(100, 30));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel13.add(jTextField1, java.awt.BorderLayout.CENTER);

        jButton8.setText("Trier");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton8, java.awt.BorderLayout.EAST);

        jPanel4.add(jPanel13);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBackground(new java.awt.Color(204, 255, 204));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel5.setPreferredSize(new java.awt.Dimension(500, 30));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jButton6.setText("Sans tri");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel3);

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jButton3.setText("Tri par coût");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jButton5.setText("Tri par date");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(204, 255, 204));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jButton4.setText("Tri par date du");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton4, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(204, 255, 204));
        jPanel9.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jTextField3.setPreferredSize(new java.awt.Dimension(70, 25));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel9.add(jTextField3, java.awt.BorderLayout.WEST);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("au");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel9.add(jLabel3, java.awt.BorderLayout.CENTER);

        jTextField2.setPreferredSize(new java.awt.Dimension(70, 25));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel9.add(jTextField2, java.awt.BorderLayout.EAST);

        jPanel5.add(jPanel9);

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel10.setBackground(new java.awt.Color(204, 255, 204));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/princetonPlainsboro/icone-fiche.png"))); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.setPreferredSize(new java.awt.Dimension(100, 25));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton1);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/princetonPlainsboro/imp.gif"))); // NOI18N
        jButton2.setText("Imprimer");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel10.add(jButton2);

        jPanel2.add(jPanel10, java.awt.BorderLayout.PAGE_END);

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initjList1() {
        jList1.setModel(dm.getModelPatient());
        jList1.addListSelectionListener(new ListSelectionListener() {

           
            @Override
            public void valueChanged(ListSelectionEvent e) {
                List<Patient> patientsSelectionnes = new Vector<Patient>();
                patientsSelectionnes = jList1.getSelectedValuesList();

                DossierMedical dossier = new DossierMedical();
                Iterator<FicheDeSoins> it = dm.getFiches().iterator();
                while (it.hasNext()) {
                    FicheDeSoins fiche = it.next();
                    if (patientsSelectionnes.contains(fiche.getPatient())) {
                       dossier.getFiches().add(fiche);
                    }
                }
                jTextArea1.setText(dossier.afficherString());
            }
        });
    }

 //affichage dossier medical
    private void initJTextArea() {
        jTextArea1.setText(dm.afficherString());
    }

    //action du bouton ajouter fiche
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AjouterFicheDeSoins ajoutFiche = new AjouterFicheDeSoins();
        ajoutFiche.setVisible(true);
        


    }//GEN-LAST:event_jButton1ActionPerformed

    public JTextArea getjTextArea1() {
        return jTextArea1;
    }

    //champ du medecin
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        int i = 0;
        while (i < dm.renvoieListeMedecins().size() && !jTextField1.getText().equals(dm.renvoieListeMedecins().get(i).getNom())) {
            i++;
        }
        if (i == dm.renvoieListeMedecins().size()) {
            JOptionPane.showMessageDialog(null, "Ce médecin n'existe pas", "Erreur", JOptionPane.ERROR_MESSAGE);
            //jTextField1.setText(null);
        }
     }//GEN-LAST:event_jTextField1ActionPerformed
    //tri par cout
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextArea1.setText(dm.afficherFichesTrieesCoutsString());
    }//GEN-LAST:event_jButton3ActionPerformed

    //sans tri
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTextArea1.setText(dm.afficherString());
    }//GEN-LAST:event_jButton6ActionPerformed

    //tri par date normal
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextArea1.setText(dm.trierString(d));
    }//GEN-LAST:event_jButton5ActionPerformed

    //tri par date du .. au ..
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (jTextField3.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "remplissez la date de début", "Erreur", JOptionPane.ERROR_MESSAGE);
        } else if (jTextField2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "remplissez la date de fin", "Erreur", JOptionPane.ERROR_MESSAGE);
        } else {
            jTextArea1.setText(dm.afficherFichesIntervalleString(StringToDate(jTextField3.getText()), StringToDate(jTextField2.getText())));
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    //la premiere date
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        jTextField3.getText();
    }//GEN-LAST:event_jTextField3ActionPerformed

    //la deuxieme date
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        jTextField2.getText();
    }//GEN-LAST:event_jTextField2ActionPerformed

    //le bouton du tri par medecin des patients
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (jTextField1.getText() != null) {
            jTextField1ActionPerformed(evt); //verification du nom de medecin
            DefaultListModel model = new DefaultListModel();
            DossierMedical dossier = new DossierMedical();
            Iterator<FicheDeSoins> it = dm.getFiches().iterator();
            while (it.hasNext()) {
                FicheDeSoins fiche = it.next();
                if (fiche.getMedecin().getNom().equals(jTextField1.getText())) {
                    model.addElement(fiche.getPatient());
                    dossier.getFiches().add(fiche);
                }
            }
            jList1.setModel(model);
            jTextArea1.setText(dossier.afficherString());
        } else if (!(jTextField1.getText() != null)) {
            jList1.setModel(dm.getModelPatient());
            jTextArea1.setText(dm.afficherString());
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    //bouton associé a la liste des patients sans tri
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.initjList1();
        jTextField1.setText(null);
        jTextArea1.setText(dm.afficherString());

    }//GEN-LAST:event_jButton7ActionPerformed

    //création d'une date à partir d'un string
    public Date StringToDate(String s) {
        int jour = Integer.parseInt(s.substring(0, s.indexOf('/')));
        int mois = Integer.parseInt(s.substring(s.indexOf('/') + 1, s.lastIndexOf('/')));
        int annee = Integer.parseInt(s.substring(s.lastIndexOf('/') + 1, s.length()));

        Date date = new Date(jour, mois, annee);
        System.out.println(date);
        return date;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceMedecin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
    LectureXML test = new LectureXML("dossiers.xml");
    DossierMedical dm = test.getDossier();
    ComparaisonFiches d = new ComparaisonFichesDates();

}
