/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package princetonPlainsboro;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author luce
 */
public class InterfaceAdmin extends javax.swing.JFrame {

    LectureXML test = new LectureXML("dossiers.xml");
    DossierMedical dm = new DossierMedical();

    public InterfaceAdmin() {
        dm = test.getDossier();
        initComponents();
        initjList1();
        initjList2(); 
        initjList3();
        initjList4();
        initjList8();
        initjList6();    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Base = new javax.swing.JPanel();
        Specialite = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList8 = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList();
        PanelMedecin = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane13 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        PanelPatient = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane9 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        Actes = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList7 = new javax.swing.JList();
        jPanel18 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de coûts");
        setBackground(java.awt.Color.black);

        Base.setBackground(new java.awt.Color(61, 81, 172));
        Base.setLayout(new java.awt.GridLayout(1, 4));

        Specialite.setBackground(new java.awt.Color(9, 139, 248));
        Specialite.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Specialite.setPreferredSize(new java.awt.Dimension(110, 327));
        Specialite.setLayout(new java.awt.BorderLayout());

        jPanel20.setBackground(new java.awt.Color(9, 140, 248));
        jPanel20.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel20.setLayout(new java.awt.GridLayout(2, 1));

        jLabel6.setText("Spécialités");
        jPanel20.add(jLabel6);

        jLabel24.setText("Nom spécialité            Coût");
        jPanel20.add(jLabel24);

        Specialite.add(jPanel20, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane8.setPreferredSize(new java.awt.Dimension(33, 80));

        jList8.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(jList8);

        jPanel2.add(jScrollPane8);

        jList6.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(jList6);

        jPanel2.add(jScrollPane6);

        Specialite.add(jPanel2, java.awt.BorderLayout.CENTER);

        Base.add(Specialite);

        PanelMedecin.setBackground(new java.awt.Color(9, 139, 248));
        PanelMedecin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelMedecin.setPreferredSize(new java.awt.Dimension(110, 327));
        PanelMedecin.setLayout(new java.awt.BorderLayout());

        jPanel17.setBackground(new java.awt.Color(9, 140, 248));
        jPanel17.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel17.setLayout(new java.awt.GridLayout(2, 1));

        jLabel25.setText("Médecins              12");
        jPanel17.add(jLabel25);

        jLabel26.setText("Nom médecin              Coût praticien");
        jPanel17.add(jLabel26);

        PanelMedecin.add(jPanel17, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane12.setViewportView(jList2);

        jPanel5.add(jScrollPane12);

        jList4.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane13.setViewportView(jList4);

        jPanel5.add(jScrollPane13);

        PanelMedecin.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel21.setBackground(new java.awt.Color(204, 204, 255));
        jPanel21.setLayout(new java.awt.BorderLayout());

        jPanel22.setLayout(new java.awt.GridLayout(1, 2));

        jButton11.setBackground(new java.awt.Color(153, 153, 255));
        jButton11.setText("Supprimer");
        jButton11.setPreferredSize(new java.awt.Dimension(55, 30));
        jPanel22.add(jButton11);

        jButton12.setBackground(new java.awt.Color(153, 153, 255));
        jButton12.setText("Ajouter");
        jButton12.setPreferredSize(new java.awt.Dimension(55, 30));
        jPanel22.add(jButton12);

        jPanel21.add(jPanel22, java.awt.BorderLayout.CENTER);

        jLabel23.setBackground(new java.awt.Color(204, 204, 255));
        jLabel23.setText("Ajouter/Supprimer patient");
        jPanel21.add(jLabel23, java.awt.BorderLayout.PAGE_START);

        PanelMedecin.add(jPanel21, java.awt.BorderLayout.PAGE_END);

        Base.add(PanelMedecin);

        PanelPatient.setBackground(new java.awt.Color(9, 139, 248));
        PanelPatient.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelPatient.setPreferredSize(new java.awt.Dimension(110, 327));
        PanelPatient.setLayout(new java.awt.BorderLayout());

        jPanel15.setBackground(new java.awt.Color(9, 140, 248));
        jPanel15.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel15.setLayout(new java.awt.GridLayout(2, 1));

        jLabel19.setText("Patients              15");
        jPanel15.add(jLabel19);

        jLabel20.setText("Nom patient              Coût soins");
        jPanel15.add(jLabel20);

        PanelPatient.add(jPanel15, java.awt.BorderLayout.PAGE_START);

        jPanel14.setBackground(new java.awt.Color(204, 204, 255));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jPanel19.setLayout(new java.awt.GridLayout(1, 2));

        jButton9.setBackground(new java.awt.Color(153, 153, 255));
        jButton9.setText("Supprimer");
        jButton9.setPreferredSize(new java.awt.Dimension(55, 30));
        jPanel19.add(jButton9);

        jButton10.setBackground(new java.awt.Color(153, 153, 255));
        jButton10.setText("Ajouter");
        jButton10.setPreferredSize(new java.awt.Dimension(55, 30));
        jPanel19.add(jButton10);

        jPanel14.add(jPanel19, java.awt.BorderLayout.CENTER);

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("Ajouter/Supprimer patient");
        jPanel14.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        PanelPatient.add(jPanel14, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane10.setPreferredSize(new java.awt.Dimension(72, 130));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(jList1);

        jPanel3.add(jScrollPane10);

        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(jList3);

        jPanel3.add(jScrollPane9);

        PanelPatient.add(jPanel3, java.awt.BorderLayout.CENTER);

        Base.add(PanelPatient);

        Actes.setBackground(new java.awt.Color(9, 139, 248));
        Actes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Actes.setPreferredSize(new java.awt.Dimension(110, 327));
        Actes.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jList5.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList5);

        jPanel4.add(jScrollPane5);

        jList7.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jList7);

        jPanel4.add(jScrollPane7);

        Actes.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel18.setBackground(new java.awt.Color(9, 140, 248));
        jPanel18.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel18.setLayout(new java.awt.GridLayout(2, 1));

        jLabel13.setText("Actes");
        jPanel18.add(jLabel13);

        jLabel18.setText("Code              Coût");
        jPanel18.add(jLabel18);

        Actes.add(jPanel18, java.awt.BorderLayout.PAGE_START);

        Base.add(Actes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //
    private void initjList1() {
        
        jList1.setModel(dm.getModelPatient());
        jList1.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent lse) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

        });
    }
    
    private void initjList2() {
        
        jList2.setModel(dm.getModelMedecin());
        jList2.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent lse) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

        });
    }


    private void initjList3() {
        jList3.setModel(dm.getModelCoutPatient());
        jList3.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent lse) {
               // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

        });
    }
    
     
    private void initjList4() {
        jList4.setModel(dm.getModelCoutMedecin());
        jList4.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent lse) {
               // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

        });
    }
    
    
    private void initjList8(){
       
              jList8.setModel(dm.getModelSpecialite());
              jList8.addListSelectionListener(new ListSelectionListener(){

         @Override
         public void valueChanged(ListSelectionEvent lse) {
             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         }
});          
             }
     private void initjList6(){
       
              jList6.setModel(dm.getModelCoutSpecialite());
              jList6.addListSelectionListener(new ListSelectionListener(){

         @Override
         public void valueChanged(ListSelectionEvent lse) {
             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         }
});          
             }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Actes;
    private javax.swing.JPanel Base;
    private javax.swing.JPanel PanelMedecin;
    private javax.swing.JPanel PanelPatient;
    private javax.swing.JPanel Specialite;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JList jList5;
    private javax.swing.JList jList6;
    private javax.swing.JList jList7;
    private javax.swing.JList jList8;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables
}
